### ISSUE TITLE
Initial components

### ISSUE THREAD

**Issue by gregnordin** [utah-MFDA/h.r.3.3_pdk#1]
- Valves of different sizes
- Pumps
- Diffusion mixing channel? (tall high aspect ratio channel - see [Spatially and optically tailored 3D printing for
highly miniaturized and integrated microfluidics](https://doi.org/10.1038/s41467-021-25788-w))
- Chip to chip interconnects? ([3D printed high density, reversible, chip-to-chip microfluidic interconnects](https://pubs.rsc.org/en/content/articlelanding/2018/lc/c7lc01113j))
- 90&deg; channel bends, vertical
- 90&deg; channel bends, horizontal
- Arc-shaped channel bends, horizontal and vertical
- Horizontal cylindrical tubing connection
- Vertical cylindrical tubing connection
- On-chip cylindrical well
- Serpentine channels
    - 2D horizontal (x-y)
    - 2D vertical (x-z and z-x)
    - 3D

**Comment by bkgale** [comment]
Other items:
Inlet
Outlet
Rectangular channel
Round channel
Expansion channel
Nozzle channel
Serpentine channel
Junction (if more than two channels connect)
There are lots of different types of valves; to start, let's pick some of Nordin's

**Comment by srtemp** [comment]
I've made separate issues for each component so that I can use them in the projects view and divide them into subtasks. 
I believe I've addressed all of them with these caveats:
- I think Inlet/outlet is the same as cylindrical tubing connections
- I think an N-way junction is a subtype of mixer

Now that I've broken the issues out I'm going to close this issue; feel free to reopen if I've missed something, or to add additional issues for any components I've missed
